django_bookmarks/urls.py
import os.path
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from bookmarks.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

site_media = os.path.join(os.path.dirname(__file__), '..','site_media')

urlpatterns = patterns('',
    # Browsing
    (r'^$', main_page),
    (r'^popular/$', popular_page),
    (r'^user/(\w+)/$', user_page),
    (r'tag/([^\s]+)/$', tag_page),
    (r'tag/$', tag_cloud_page),
    (r'^search/$', search_page),
    (r'^bookmark/(\d+)/$', bookmark_page),
    
    # Comments
    (r'^comments/', include('django.contrib.comments.urls')),
    
    # Ajax
    (r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
    
    #Session management
    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^register/$', register_page),
    (r'^register/success/$', direct_to_template,
     { 'template': 'registration/register_success.html' }),
    
    #Mdedia files
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
       { 'document_root': site_media }),
                       
    #Account management
    (r'^save/$', bookmark_save_page),
    (r'^vote/$', bookmark_vote_page),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    #Friends
    (r'^friends/(\w+)/$', friends_page),
    (r'^friend/add/$', friend_add),
)

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.template.loader import get_template
from django.template import Context
from django.conf import settings

class Link(models.Model):
    url = models.URLField(unique=True)
    def __str__(self):
        return self.url
    
    class Admin:
        pass

class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.link.url)
    
    class Admin:
        pass

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)
    def __str__(self):
        return self.name
    
    class Admin:
        pass

class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)
    def __str__(self):
        return '%s, %s' % self.bookmark, self.votes
    
    class Admin:
        pass
    
class Friendship(models.Model):
  from_friend = models.ForeignKey(User, related_name='friend_set')
  to_friend = models.ForeignKey(User, related_name='to_friend_set')
  
  def __str__(self):
    return '%s, %s' % (self.from_friend.username, self.to_friend.username)

  class Admin:
    pass

  class Meta:
    unique_together = (('to_friend', 'from_friend'), )


class Invitation(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    sender = models.ForeignKey(User)
    def __str__(self):
        return '%s, %s' % (self.sender.username, self.email)
    class Admin:
        pass
    def send(self):
        subject = 'Invitation to join Django Bookmarks'
        link = 'http://%s/friend/accept/%s/' % (settings.SITE_HOST,
                                                self.code)
        template = get_template('invitation_email.txt')
        context = Context({'name': self.name,
                           'link': link,
                           'sender': self.sender.username,})
        message = template.render(context)
        send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email])

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title>Django Bookmarks | {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
  <script type="text/javascript" src="/site_media/jquery.js"></script>
  {% block external %}{% endblock %}
  <link rel="stylesheet" type="text/css" href="/site_media/jqueryslidemenu.css" />
  <!--[if lte IE 7]>
  <style type="text/css">
  html .jqueryslidemenu{height: 1%;} /*Holly Hack for IE7 and below*/
  </style>
  <![endif]-->
  <script type="text/javascript" src="jqueryslidemenu.js"></script>
</head>

<body>
<div id="bg_middle">
  <div id="bg_header">
    <div id="container">
      <!-- MAIN NAVIGATION -->
      <div id="nav" class="jqueryslidemenu">
      <ul>
          <li><a href="/">home</a></li>
          <li><a href="/popular/">popular</a></li>
          {% if user.is_authenticated %}
          <li><a href="/save/">submit</a></li>
          <li><a href="/search/">search</a></li>
          <li><a href="/user/{{ user.username }}/"> {{ user.username }} </a></li>
          <li><a href="/logout/">logout</a></li>
          {% else %}
          <li><a href="/login/">login</a></li>
          <li><a href="/register/">register</a></li>
          {% endif %}
          <br style="clear: right" />
        </ul>
      </div>
      <!-- HEADER -->
      <div id="header">
        {% block head %}{% endblock %}
      </div>
      <!-- CONTENT -->
      <div id="content_left">
      {% block content %}{% endblock %}     
    </div>

  </div>
</div>
</body>
</html>

templates/bookmark_list.html
{% if bookmarks %}
  <ul class="bookmarks">
    {% for bookmark in bookmarks %}
      <li>
        <a href="{{ bookmark.link.url }}" class="title">
          {{ bookmark.title|escape }}</a>
        {% if show_edit %}
          <a href="/save/?url={{ bookmark.link.url|urlencode }}"
            class="edit">[edit]</a>
        {% endif %}
        <br />
        {% if show_tags %}
          Tags: 
          {% if bookmark.tag_set.all %}
            <ul class="tags">
              {% for tag in bookmark.tag_set.all %}
                <li><a href="/tag/{{ tag.name|urlencode }}/">
                  {{ tag.name|escape }}</a></li>
              {% endfor %}
            </ul>
          {% else %}
            None.
          {% endif %}
          <br />
        {% endif %}
        {% if show_user %}
          Posted By: 
          <a href="/user/{{ bookmark.user.username }}/" class="username">
            {{ bookmark.user.username }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% if show_paginator %}
    <div class="paginator">
      <span class="step-links">
      {% if bookmarks.has_previous %}
        <a href="?page={{ prev_page }}">&laquo; Previous</a>
      {% endif %}
      
      {% for page in bookmarks.paginator.page_range %}
        {% ifequal page bookmarks.number %}
        <span class="current page">{{ page }}</span>
        {% else %}
        <a href="?page={{ page }}"> {{ page }}</a>
        {% endifequal %} 
      {% endfor %}
      
      {% if bookmarks.has_next %}
        <a href="?page={{ next_page }}">Next &raquo;</a>
      {% endif %}
      </span>
    </div>
  {% endif %}
{% else %}
  <p>No bookmarks found.</p>
{% endif %}

templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}

{% block title %}Bookmark: {{ shared_bookmark.bookmark.title|escape }}{% endblock %}

{% block head %}
  <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
  <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
  {{ shared_bookmark.bookmark.title|escape }}</a>
{% endblock %}

{% block content %}
  Posted By: 
  <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">
    {{ shared_bookmark.bookmark.user.username }}</a> |
  <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>

  <h2>Comments</h2>
  {% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}
  {% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}

  {% for comment in comment_list %}
    <div class="comment">
      <p><b>{{ comment.user.username }}</b> said:</p>
      {{ comment.comment|escape|urlizetrunc:40|linebreaks }}
    </div>
  {% endfor %}

  <p>Number of comments: {{ comment_count }}</p>
  
  {% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id %}
{% endblock %}

templates/bookmark_save.html
{% extends "base.html" %}

{% block external %}
  <link rel="stylesheet" href="/site_media/jquery.autocomplete.css" type="text/css" />
  <script type="text/javascript" src="/site_media/dimensions.js"> </script>
  <script type="text/javascript" src="/site_media/jquery.bgiframe.min.js"> </script>
  <script type="text/javascript" src="/site_media/jquery.autocomplete.js"> </script>
  <script type="text/javascript" src="/site_media/tag_autocomplete.js"> </script>
{% endblock %}

{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}

{% block content %}
{% include 'bookmark_save_form.html' %}
{% endblock %}

templates/bookmark_save_form.html
<form id="save-form" method="post" action="/save/">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save" />
</form>

templates/friends_page.html
{% extends "base.html" %}

{% block title %}Friends for {{ username }}{% endblock %}
{% block head %}Friends for {{ username }}{% endblock %}

{% block content %}
  <h2>Friend List</h2>
  {% if friends %}
    <ul class="friends">
      {% for friend in friends %}
        <li><a href="/user/{{ friend.username }}/">{{ friend.username }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No friends found.</p>
  {% endif %}
  <a href="/friend/invite/">Invite a friend!</a>

  <h2>Latest Friend Bookmarks</h2>
  {% include 'bookmark_list.html' %}
{% endblock %}

templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Django Bookmarks{% endblock %}
{% block head %}Welcome to Django Bookmarks{% endblock %}
{% block content %}
  {% if user.username %}
    <p>Welcome {{ user.username }}!
      Here you can store and share bookmarks!</p>
  {% else %}
    <p>Welcome anonymous user!
      You need to <a href="/login/">login</a>
      before you can store and share bookmarks.</p>
  {% endif %}
  <h2>Bookmarks Shared by Users</h2>
    {% include 'shared_bookmark_list.html' %}
{% endblock %}

templates/popular_page.html
{% extends "base.html" %}

{% block title %}Popular Bookmarks{% endblock %}
{% block head %}Popular Bookmarks{% endblock %}

{% block content %}
  {% include 'shared_bookmark_list.html' %}
{% endblock %}

templates/search.html
{% extends "base.html" %}

{% block external %}
  <script type="text/javascript" src="/site_media/search.js"></script>
{% endblock %}

{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}

{% block content %}
<form id="search-form" method="get" action=".">
  {{ form.as_p }}
  <input type="submit" value="search" />
</form>

<div id="search-results">
  {% if show_results %}
    {% include 'bookmark_list.html' %}
  {% endif %}
</div>

{% endblock %}

templates/shared_bookmark_list.html
{% if shared_bookmarks %}
  <ul class="bookmarks">
    {% for shared_bookmark in shared_bookmarks %}
      <li>
        <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
        <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">
          {{ shared_bookmark.bookmark.title|escape }}</a>
        <br/>
        Posted By: 
        <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">
          {{ shared_bookmark.bookmark.user.username }}</a> |
        <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span> |
        <a href="/bookmark/{{ shared_bookmark.id}}/">Comments</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No bookmarks found.</p>
{% endif %}

templates/tag_cloud_page.html
{% extends "base.html" %}

{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}

{% block content %}
  <div id="tag-cloud">
    {% for tag in tags %}
      <a href="/tag/{{ tag.name|urlencode }}/"
      class="tag-cloud-{{ tag.weight }}">
        {{ tag.name|escape }}</a>
    {% endfor %}
  </div>
{% endblock %}

templates/tag_page.html
{% extends "base.html" %}

{% block title %}Tag: {{ tag_name|escape }}{% endblock %}
{% block head %}Bookmarks for tag: {{ tag_name|escape }}{% endblock %}

{% block content %}
  {% include "bookmark_list.html" %}
{% endblock %}

templates/user_page.html
{% extends "base.html" %}

{% block external %}
  <script type="text/javascript" src="/site_media/bookmark_edit.js"></script>

{% endblock %}

{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}

{% block content %}
   {% ifequal user.username username %}
     <a href="/friends/{{ username }}/">view your friends</a>
   {% else %}
     {% if is_friend %}
       <a href="/friends/{{ user.username }}/">
                         {{ username }} is a friend of yours</a>
     {% else %}
       <a href="/friend/add/?username={{ username }}">
                         add {{ username }} to your friends</a>
     {% endif %}
     - <a href="/friends/{{ username }}/">
                    view {{username }}'s friends</a>
   {% endifequal %}
{% include 'bookmark_list.html' %}
{% endblock %}